# SPDX-FileCopyrightText: 2025 Chris Rizzitello <sithlord48@gmail.com>
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "TuPig Synergy"
SPDX-PackageSupplier = "TuPig"
SPDX-PackageDownloadLocation = "https://github.com/Tupig/Tupig_synergy"

[[annotations]]
path = [
   ".clang-format"
 , ".editorconfig"
 , ".gitattributes"
 , ".gitignore"
 ,    "cspell.json"
 ,    "config/sonar-project.properties"
 , "**/*.md"
 , "docs/**"
  , "deploy/windows/wix-patch.xml.in"
  , "src/apps/deskflow-core/deskflow-core.exe.manifest"
  , "src/apps/res/manpage.txt"
  , "src/apps/res/deskflow.plist.in"
  , "src/apps/res/entitlements-dev.plist"
  , "translations/*.ts"
]
SPDX-FileCopyrightText = "TuPig"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
   "deploy/mac/dmg-volume.icns"
 , "deploy/windows/wix-banner.png"
 , "deploy/windows/wix-dialog.png"
 , "src/apps/res/icons/deskflow-**/apps/64/org.deskflow.deskflow*.svg"
 , "extra/src/apps/res/synergy.qrc"
]
SPDX-FileCopyrightText = "TuPig"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = "src/apps/res/icons/deskflow-**/**/**/**.svg"
SPDX-FileCopyrightText = "Kde Breeze Icons"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = "src/apps/res/icons/deskflow-**/index.theme"
SPDX-FileCopyrightText = "Chris Rizzitello <sithlord48@gmail.com>"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = [
   "src/lib/gui/MainWindow.ui"
 , "src/lib/gui/dialogs/*.ui"
]
SPDX-FileCopyrightText = "TuPig"
SPDX-License-Identifier = "GPL-2.0-only WITH LicenseRef-OpenSSL-Exception"
