# SPDX-FileCopyrightText: 2025 Chris Rizzitello <sithlord48@gmail.com>
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "TuPig Synergy"
SPDX-PackageSupplier = "TuPig"
SPDX-PackageDownloadLocation = "https://github.com/Tupig/Tupig_synergy"

[[annotations]]
path = [
   ".clang-format"
 , ".editorconfig"
 , ".gitattributes"
 , ".gitignore"
 ,    "cspell.json"
 , "CMakePresets.json"
 , "setup.bat"
 , "vcpkg.json"
 , "scripts/bootstrap-vcpkg.bat"
 , "scripts/bootstrap-vcpkg.sh"
 , "scripts/build.bat"
 , "scripts/build.sh"
 , "scripts/ci/ci-windows-signing.bat"
 , "triplets/overlay/arm64-osx.cmake"
 , "triplets/overlay/arm64-windows-static.cmake"
 , "triplets/overlay/x64-linux.cmake"
 , "triplets/overlay/x64-osx.cmake"
 , "triplets/overlay/x64-windows-static.cmake"
 , "triplets/overlay/x64-windows.cmake"
 ,    "config/sonar-project.properties"
 , "config/Synergy.test.example.conf"
 , "deploy/linux/flatpak/ci-build-lint-exceptions.json"
 , "deploy/mac/synergy-eula.txt"
 , "**/*.md"
 , "docs/**"
  , "deploy/windows/wix-patch.xml.in"
  , "src/apps/synergy-core/synergy-core.exe.manifest"
  , "src/apps/res/manpage.txt"
  , "src/apps/res/synergy.plist.in"
  , "src/apps/res/entitlements-dev.plist"
  , "translations/*.ts"
]
SPDX-FileCopyrightText = "TuPig"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
   "deploy/mac/dmg-volume.icns"
 , "deploy/mac/dmg-background.tiff"
 , "deploy/mac/bundle/Contents/Resources/TuPig Synergy.icns"
 , "deploy/windows/wix-banner.png"
 , "deploy/windows/wix-dialog.png"
 , "src/apps/res/icons/synergy-**/apps/64/com.tupig.synergy*.svg"
 , "src/apps/res/branding/image/logo-dark.png"
 , "src/apps/res/branding/image/logo-light.png"
 , "src/apps/res/branding/synergy-dark.theme"
 , "src/apps/res/branding/synergy-light.theme"
 , "src/apps/res/branding/synergy-symbolic-dark.svg"
 , "src/apps/res/branding/synergy-symbolic-light.svg"
 , "src/apps/res/branding/synergy.ico"
 , "src/apps/res/branding/synergy.png"
 , "src/apps/res/branding/synergy.qrc"
 , "src/apps/res/branding/synergy.svg"
]
SPDX-FileCopyrightText = "TuPig"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = "src/apps/res/icons/synergy-**/**/**/**.svg"
SPDX-FileCopyrightText = "Kde Breeze Icons"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = "src/apps/res/icons/synergy-**/index.theme"
SPDX-FileCopyrightText = "Chris Rizzitello <sithlord48@gmail.com>"
SPDX-License-Identifier = "LGPL-2.1-only"

[[annotations]]
path = [
   "src/lib/gui/MainWindow.ui"
 , "src/lib/gui/dialogs/*.ui"
]
SPDX-FileCopyrightText = "TuPig"
SPDX-License-Identifier = "GPL-2.0-only WITH LicenseRef-OpenSSL-Exception"
