[Icon Theme]
Name=synergy-dark
Comment=TuPig Synergy dark (action icons aliased from upstream deskflow set)
DisplayDepth=32
FollowsColorScheme=true
Example=folder
DesktopDefault=48
ToolbarDefault=22
MainToolbarDefault=22
SmallDefault=16
PanelDefault=48
DialogDefault=32
KDE-Extensions=.svg

Directories=actions/16,actions/22,actions/24,actions/32,apps/64,devices/64,places/64,status/64

[apps/64]
Size=64
Context=Applications
Type=Scalable
MinSize=22
MaxSize=256

[actions/16]
Size=16
Context=Actions
Type=Scalable
MinSize=16
MaxSize=256

[actions/22]
Size=22
Context=Actions
Type=Scalable
MinSize=16
MaxSize=256

[actions/24]
Size=24
Context=Actions
Type=Scalable
MinSize=16
MaxSize=256

[actions/32]
Size=32
Context=Actions
Type=Scalable
MinSize=16
MaxSize=256

[places/64]
Size=64
Type=Scalable
Context=Places
MinSize=48
MaxSize=256

[status/64]
Size=64
Context=Status
Type=Scalable
MinSize=22
MaxSize=256

[devices/64]
Size=64
Context=Devices
Type=Scalable
MinSize=22
MaxSize=256
