blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/Tupig/TuPig_Product/discussions/new?category=q-a
    about: Where to ask general questions.
  - name: Show and Tell
    url: https://github.com/Tupig/TuPig_Product/discussions/new?category=show-and-tell
    about: Show off things you have done with TuPig Synergy
  - name: Documentation
    url: https://github.com/Tupig/TuPig_Product/tree/main/synergy/docs
    about: Build guide, configuration, protocol and troubleshooting docs.
